#analysis_options.yaml
include: package:flutter_lints/flutter.yaml
linter:
  rules:
    non_constant_identifier_names: true
    use_named_constants: true

analyzer:
  exclude:
    - /**/**.g.dart
    - /**/**.freezed.dart
    - /**/generated/**
