name: portfolio
description: "Omar's Portfolio"
publish_to: 'none'

version: 3.1.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  equatable: ^2.0.5
  pocketbase: ^0.22.0
  flutter_bloc: ^9.0.0
  flutter_screenutil: ^5.9.3
  go_router: ^14.6.0
  flutter_svg: ^2.0.14
  auto_animated: ^3.2.0
  pull_down_button: ^0.10.2
  ionicons: ^0.2.2
  url_launcher: ^6.3.1
  freezed_annotation: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  cached_network_image: ^3.4.1
  skeletonizer: ^1.4.3
  flutter_markdown: ^0.7.6+2
#  photo_view: ^0.15.0
#  cached_network_image_platform_interface: ^4.1.1
  get_it: ^8.0.3
  el_tooltip: ^2.2.1
  share_plus: ^10.1.4
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
#  timelines_plus: ^1.0.4

#flutter_gen:
#  output: lib/core/generated # Optional (default: lib/gen/)
#  line_length: 120 # Optional (default: 80)

dev_dependencies:
  freezed: ^3.0.4
  build_runner:
  flutter_gen_runner:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true



  # run this to generate assets:
  # flutter pub global activate
  # fgen -n AppAssets -o lib/core/const/resource.dart

  assets:
    - assets/svg/
    - assets/webp/
    - assets/svg/icons/


